spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.0.144:3306/babymeal
    username: root
    password: green502
  jpa:
    hibernate:
      ddl-auto: update # Entity? ??? ?? ???? ???.
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    path: /swagger.html
